# Base para o projeto
name: base para projeto

on: [push]
# quais trabalhos seráo executados ao fazer um push
jobs:
  info:
    runs-on: ubuntu-lastest
    steps:
      - name: Lista diretorio base
        run: ls -la 
        
