name: Base para o projeto

on: 
  push:
    branches:
      - main 
    paths:
      - 'teste/**'   # só executa se push no diretorio teste  
  workflow_dispatch:
    inputs:
      environment:
        description: Ambiente de teste
        type: choice
        required: true
        default: dev
        options:
          - web
          - macOs
          - android
          

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Lista diretorio
        run: ls -la
      # listar as variaveis de contexto do github
      - name: Lista as variaveis de contexto
        run: echo "${{ toJson(github) }}"
