# primeiro yml para actions
name: primeiro arquivo actions

# qual será o gatilho para execuçao do job
on: 
  push:
    branches:
      - dev
    paths:
      - 'teste/**'    # somente executa se push no diretorio teste  

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: web
        options:
          - web
          - macOs
          - windows
          - android 
          
jobs:
  lista_dir:
    runs-on: ubuntu-lastest
    steps:
      - name: Lista diretorio
        run: echo ls -la 
  teste_funcional:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v6
      - name: verifica se fez corretamente
        run:  ls -la
      - name: Instala o Node na maquina virtual        
        uses: actions/setup-node@v6
      - name: Instala as dependencias do projeto
        working-directory: e2e-tests 
        run: npm ci    
      - name: Roda os testes Funcionais
        if: success() 
        working-directory: e2e-tests
        run: npm run test 
        env:
          API_URL: http://gceic26-102.onrender.com
          SITE_URL: http://gceic26-102-app.onrender.com
        
      - name: verifica se fez corretamente
        working-directory: e2e-tests 
        run:  ls -la          
      - name: fotos da tela
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Fotos dos testes
          # Path to the release files
          # Gravar as fotos na raiz do projeto no docker

          # path: /home/runner/work//aula_teste_101/aula_teste_101/e2e-tests/screenshots/**/*.png
          path: /home/runner/work//GCEIC26-102/GCEIC26-102/e2e-tests/screenshots/*.png
